### ISSUE TITLE
Tindie link is broken

### ISSUE THREAD

**Issue by NeoFromMatrix** [voltlog/Voltlogger#1]
Tindie link in the main Readme.md redirects to https://www.tindie.com/stores/products/ which shows a tindie 404 page

**Comment by magicsmoke** [comment]
It might be a valid link but the listing is hidden for the moment before it is ready to be sold!

**Comment by voltlog** [comment]
> Tindie link in the main Readme.md redirects to https://www.tindie.com/stores/products/ which shows a tindie 404 page

Sorry, I'm working on adding the new listing on Tindie, I'll update the link soon.

**Comment by voltlog** [comment]
Product is now live on Tindie.
