### ISSUE TITLE
USB-C Receptical

### ISSUE THREAD

**Issue by jfnk324** [voltlog/Voltlogger#2]
Hello, thank you for your design. I was looking for a source for your USB-C plug, as I couldn't find one that also has data pins. Can you provide a link to the product you used?

**Comment by voltlog** [comment]
Part number is Korean Hroparts Elec TYPE-C-31-M-12. I usually specify the pn for these parts in the symbol properties in the schematic editor.

**Comment by jfnk324** [comment]
Thank you very much, sir!
